### PR TITLE
Use project version of ng instead of global

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by mraible** [comment]
Why is this needed? Does `yarn start` work?

**Comment by bdemers** [comment]
the current run script assumes you have `ng` installed globally.  I didn't, but it is available in the node_modules, so `yarn run` setups that environment and allows `ng` to be run from the local copy.
You could also use `./node_modules/.bin/ng` directly.

**Comment by bdemers** [comment]
still early, sorry.... miss read your comment `yarn start` does work

**Comment by mraible** [comment]
Fixed via https://github.com/mraible/cloud-native-pwas/pull/7/commits/cd2dabb46c2794bdefe69a5b067d7ca2a6601c46.

**Pull request closed without merging**
